version: "3.9"

services:
  app-next:
    image: "node:16.18"
    container_name: app-next
    working_dir: /usr/www/app
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - "./:/usr/www/app/"
    command: "/bin/sh  install.sh"
    networks:
      - app-fullstack

networks:
  app-fullstack:
